### ISSUE TITLE
Merging into common

### ISSUE THREAD

**Issue by parenthetical-e** [srcole/neurosrc#1]
Scott,

We should think about merging this PAC code, with some of my spectral routines, along with your 'palettes', into a common voytek spectral analysis module. 'voytoys' perhaps? 

In the meantime, I'm stealing the PAC stuff.

**Comment by parenthetical-e** [comment]
To those ends consider making 'sim_PACoutput.py' into a notebook, and expanding it a bit.  Or into formal tests. Or both, really.

**Comment by srcole** [comment]
Agreed. This is already in voytoys/scott, too. I'll need to seek your advice on what constitutes a formal test, but we can definitely do this in the next few weeks.
